/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Session;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class AdminDashboard extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private JLabel activeLabel;
    private final Color defaultColor = new Color(51, 51, 51);
    private final Color hoverColor = new Color(70, 70, 70);
    private final Color activeColor = new Color(90, 90, 90);

    public AdminDashboard() throws SQLException {
        initComponents();
        setTitle("Admin Dashboard");
        setLocationRelativeTo(null);
        setResizable(false);

        cardLayout = new CardLayout();
        mainContent.setLayout(cardLayout);

        mainContent.add(new AdminDashboardPanel(), "Dashboard");
        mainContent.add(new AdminViewProfilePanel(), "Profile");
        mainContent.add(new ManageUsersPanel(), "Users");
        mainContent.add(new AdminManageCurriculumPanel(), "Curriculum");
        mainContent.add(new AdminManageSectionsPanel(), "Sections");
        mainContent.add(new AdminManageFacultyPanel(), "Faculty");
        mainContent.add(new AdminManageFacultyAssignmentPanel(), "Assignment");
        mainContent.add(new ManageStudentsPanel(), "Students");
        mainContent.add(new AdminManageEnrollmentPanel(), "Enrollment");
        mainContent.add(new AdminHistoryPanel(), "History");
       
        addPadding(lblDashboard);
        addPadding(lblViewProfile);
        addPadding(lblManageUsers);
        addPadding(lblManageCurriculum);
        addPadding(lblManageSections);
        addPadding(lblManageFaculty);
        addPadding(lblManageFAssignment);
        addPadding(lblManageStudents);
        addPadding(lblManageEnrollment);
        addPadding(lblHistory);

        addSidebarListeners();

        setActiveLabel(lblDashboard);
        cardLayout.show(mainContent, "Dashboard");
    }
    
    private void addPadding(JLabel label) {
        label.setOpaque(true);
        label.setBackground(defaultColor);
        label.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createMatteBorder(0, 5, 0, 0, defaultColor), // left line
            BorderFactory.createEmptyBorder(10, 20, 10, 20) // padding
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblManageUsers = new javax.swing.JLabel();
        lblManageCurriculum = new javax.swing.JLabel();
        lblManageSections = new javax.swing.JLabel();
        lblManageFaculty = new javax.swing.JLabel();
        lblManageFAssignment = new javax.swing.JLabel();
        lblManageStudents = new javax.swing.JLabel();
        lblManageEnrollment = new javax.swing.JLabel();
        lblHistory = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblViewProfile = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(51, 51, 51));
        sidebar.setForeground(new java.awt.Color(51, 51, 51));

        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard");

        lblManageUsers.setForeground(new java.awt.Color(255, 255, 255));
        lblManageUsers.setText("Manage Users");

        lblManageCurriculum.setForeground(new java.awt.Color(255, 255, 255));
        lblManageCurriculum.setText("Manage Curriculum");

        lblManageSections.setForeground(new java.awt.Color(255, 255, 255));
        lblManageSections.setText("Manage Sections");

        lblManageFaculty.setForeground(new java.awt.Color(255, 255, 255));
        lblManageFaculty.setText("Manage Faculty");

        lblManageFAssignment.setForeground(new java.awt.Color(255, 255, 255));
        lblManageFAssignment.setText("Manage F. Assignment");

        lblManageStudents.setForeground(new java.awt.Color(255, 255, 255));
        lblManageStudents.setText("Manage Students");

        lblManageEnrollment.setForeground(new java.awt.Color(255, 255, 255));
        lblManageEnrollment.setText("Manage Enrollment");

        lblHistory.setForeground(new java.awt.Color(255, 255, 255));
        lblHistory.setText("History");

        btnLogout.setText("Log out");

        lblViewProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblViewProfile.setText("View Profile");

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewProfile)
                    .addComponent(lblDashboard)
                    .addComponent(lblManageUsers)
                    .addComponent(lblManageCurriculum)
                    .addComponent(lblManageSections)
                    .addComponent(lblManageFaculty)
                    .addComponent(lblManageFAssignment)
                    .addComponent(lblManageStudents)
                    .addComponent(lblHistory)
                    .addComponent(lblManageEnrollment)))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblViewProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblManageUsers)
                .addGap(5, 5, 5)
                .addComponent(lblManageCurriculum)
                .addGap(5, 5, 5)
                .addComponent(lblManageSections)
                .addGap(5, 5, 5)
                .addComponent(lblManageFaculty)
                .addGap(5, 5, 5)
                .addComponent(lblManageFAssignment)
                .addGap(5, 5, 5)
                .addComponent(lblManageStudents)
                .addGap(5, 5, 5)
                .addComponent(lblManageEnrollment)
                .addGap(5, 5, 5)
                .addComponent(lblHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(48, 48, 48))
        );

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(926, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN DASHBOARD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(676, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSidebarListeners() {
        lblDashboard.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "Dashboard");
                setActiveLabel(lblDashboard);
            }
        });
        
        lblViewProfile.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "Profile");
                setActiveLabel(lblViewProfile);
            }
        });

        lblManageUsers.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "Users");
                setActiveLabel(lblManageUsers);
            }
        });

        lblManageCurriculum.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "Curriculum");
                setActiveLabel(lblManageCurriculum);
            }
        });
        
        lblManageSections.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "Sections");
                setActiveLabel(lblManageSections);
            }
        });
        
        lblManageFaculty.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "Faculty");
                setActiveLabel(lblManageFaculty);
            }
        });
        
        lblManageFAssignment.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "Assignment");
                setActiveLabel(lblManageFAssignment);
            }
        });
        
        lblManageStudents.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "Students");
                setActiveLabel(lblManageStudents);
            }
        });
        
        lblManageEnrollment.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "Enrollment");
                setActiveLabel(lblManageEnrollment);
            }
        });
        
        lblHistory.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                cardLayout.show(mainContent, "History");
                setActiveLabel(lblHistory);
            }
        });

        btnLogout.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int confirm = JOptionPane.showConfirmDialog(
                    AdminDashboard.this,
                    "Are you sure you want to logout?",
                    "Logout",
                    JOptionPane.YES_NO_OPTION
                );
                if (confirm == JOptionPane.YES_OPTION) {
                    Session.clear();
                    dispose();
                    new LoginFrame().setVisible(true);
                }
            }
        });

        // hover effect
        addHoverEffect(lblDashboard);
        addHoverEffect(lblViewProfile);
        addHoverEffect(lblManageUsers);
        addHoverEffect(lblManageCurriculum);
        addHoverEffect(lblManageSections);
        addHoverEffect(lblManageFaculty);
        addHoverEffect(lblManageFAssignment);
        addHoverEffect(lblManageStudents);
        addHoverEffect(lblManageEnrollment);
        addHoverEffect(lblHistory);
    }

    private void addHoverEffect(JLabel label) {
        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (label != activeLabel) {
                    label.setBackground(hoverColor);
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if (label != activeLabel) {
                    label.setBackground(defaultColor);
                }
            }
        });
    }

    private void setActiveLabel(JLabel newActive) {
        if (activeLabel != null) {
            activeLabel.setBackground(defaultColor);
            activeLabel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 5, 0, 0, defaultColor),
                BorderFactory.createEmptyBorder(10, 20, 10, 20)
            ));
        }
        activeLabel = newActive;
        activeLabel.setBackground(activeColor);
        activeLabel.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createMatteBorder(0, 5, 0, 0, Color.WHITE),
            BorderFactory.createEmptyBorder(10, 20, 10, 20)
        ));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblManageCurriculum;
    private javax.swing.JLabel lblManageEnrollment;
    private javax.swing.JLabel lblManageFAssignment;
    private javax.swing.JLabel lblManageFaculty;
    private javax.swing.JLabel lblManageSections;
    private javax.swing.JLabel lblManageStudents;
    private javax.swing.JLabel lblManageUsers;
    private javax.swing.JLabel lblViewProfile;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
