/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.UserDAO;
import Model.User;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ManageUsersPanel extends javax.swing.JPanel {

    private UserDAO userDAO = new UserDAO();
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form ManageUsersPanel
     */
    public ManageUsersPanel() {
        initComponents();
        initTable();
        loadUsers();
        addLogic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAddUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        cbRole = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        lblUserId = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();

        jScrollPane1.setToolTipText("");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        btnAddUser.setText("Add User");

        btnUpdateUser.setText("Update User");

        btnDeleteUser.setText("Delete User");

        btnRefresh.setText("Refresh Table");

        lblUsername.setText("Username:");

        lblRole.setText("Role:");

        lblStatus.setText("Status:");

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "ADMIN", "FACULTY", "STUDENT" }));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "ACTIVE", "INACTIVE" }));

        btnClear.setText("Clear Fields");

        lblUserId.setText("User ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRole)
                                .addGap(49, 49, 49)
                                .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatus)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh)))
                .addGap(41, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserId)
                            .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRole))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnAddUser)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnClear)
                    .addComponent(btnUpdateUser))
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLogic() {
        btnRefresh.addActionListener(e -> {
                System.out.println("Table Refreshed.");
                loadUsers();
        });
                
        // Select row → populate fields
        tblUsers.getSelectionModel().addListSelectionListener(e -> {
            int row = tblUsers.getSelectedRow();
            if (row != -1) {
                txtUserId.setText(String.valueOf(tableModel.getValueAt(row, 0)));
                txtUsername.setText((String) tableModel.getValueAt(row, 1));
                cbRole.setSelectedItem((String) tableModel.getValueAt(row, 2));
                cbStatus.setSelectedItem((String) tableModel.getValueAt(row, 3));
            }
        });

        // Add User
        btnAddUser.addActionListener(e -> {
            String username = txtUsername.getText().trim();
            String role = (String) cbRole.getSelectedItem();
            String status = (String) cbStatus.getSelectedItem();

            if (username.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username is required.");
                return;
            }

            String defaultPassword = "password";
            
            User u = new User();
            u.setUsername(username);
            u.setPassword(defaultPassword);
            u.setRole(role);
            u.setStatus(status);

            userDAO.addUser(u);
            getAllUsers();
            clearFields();
            
            System.out.println("User " + "'" + username + "'" + "successfully added.");
            
            JOptionPane.showMessageDialog(this, "User added successfully with default password: \"password\"");
        });

        // Update User
        btnUpdateUser.addActionListener(e -> {
            int row = tblUsers.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Please select a user to update.");
                return;
            }

            int userId = (int) tableModel.getValueAt(row, 0);
            String username = txtUsername.getText().trim();
            String role = (String) cbRole.getSelectedItem();
            String status = (String) cbStatus.getSelectedItem();

            User u = new User();
            u.setUserId(userId);
            u.setUsername(username);
            u.setRole(role);
            u.setStatus(status);

            userDAO.updateUser(u);
            getAllUsers();
            clearFields();
            
            System.out.println("User " + "'" + userId + "'" + " successfully updated.");
            JOptionPane.showMessageDialog(this, "User updated successfully!");
        });

        // Delete User
        btnDeleteUser.addActionListener(e -> {
            int row = tblUsers.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Please select a user to delete.");
                return;
            }
            int userId = (int) tableModel.getValueAt(row, 0);
            int confirm = JOptionPane.showConfirmDialog(this, "Delete this user?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                userDAO.deleteUser(userId);
                getAllUsers();
                clearFields();
                
                System.out.println("User " + "'" + userId + "'" + " successfully deleted.");
                JOptionPane.showMessageDialog(this, "User deleted successfully!");
            }
        });

        // Clear
        btnClear.addActionListener(e -> clearFields());
    }
    
    private void initTable() {
        tableModel = new DefaultTableModel(
                new Object[]{"User ID", "Username", "Role", "Status"}, 0
        );
        tblUsers.setModel(tableModel);
        tblUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        getAllUsers();
    }
    
    private void getAllUsers() {
        tableModel.setRowCount(0);
        List<User> users = userDAO.getAllUsers();
        for (User u : users) {
            tableModel.addRow(new Object[]{
                    u.getUserId(),
                    u.getUsername(),
                    u.getRole(),
                    u.getStatus()
            });
        }
    }
    
    private void clearFields() {
        txtUserId.setText("");
        txtUsername.setText("");
        cbRole.setSelectedIndex(0);
        cbStatus.setSelectedIndex(0);
        tblUsers.clearSelection();
    }
    
    private void loadUsers() {
        tableModel.setRowCount(0); // clear table
        List<User> users = userDAO.getAllUsers();
        for (User user : users) {
            tableModel.addRow(new Object[]{
                user.getUserId(),
                user.getUsername(),
                user.getRole(),
                user.getStatus()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
